site_name: Harshad Ghodke — Portfolio
site_url: https://hghodkephd.github.io/hg-portfolio/
theme:
  name: material
nav:
  - Home: index.md
  - Résumé: resume.md
  - Projects:
      - Selected Projects: projects.md
      - AI-Guided Protein Design: ai-guided-protein-design.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
